[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
crt = "crnXvAtgkLMzJKEFdveTZ4Redy3mHa1YY9UXP9wZ91c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "tLnTQf4jddakRXHsbRWnSrtV6t6addFNgf6kypPv2kE.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
